# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - builder: zig
    flags: ["-Doptimize=ReleaseSmall"]
    targets: ["aarch64-linux", "aarch64-macos", "x86_64-linux"]
