# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - builder: zig
    flags: ["-Doptimize=ReleaseSmall"]
    targets: ["aarch64-linux", "aarch64-macos", "x86_64-linux"]

# what to put in the tgz files
archives:
  - wrap_in_directory: true
    files:
      - README.md
      - LICENSE*
      - extra/tennis.1

# turn stuff off
announce: { skip: true }
changelog: { disable: true }

# brew tap
brews:
  - repository: { owner: "gurgeous", name: "homebrew-tap" }
    description: Stylish CSV tables in your terminal.
    homepage: https://github.com/gurgeous/tennis
    test: system "./tennis --version"
    extra_install: |
      man1.install "extra/tennis.1"
