[package]
name = "tennis"
version = "0.7.1"
edition = "2024"
rust-version = "1.96"
license = "MIT"
description = "Stylish CSV tables in your terminal"
publish = false
repository = "https://github.com/gurgeous/tennis"

[dependencies]
anstyle = "1"
anstream = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
memchr = "2"
natord = "1"
num-format = "0.4"
rand = "0.8"
shell-words = "1"
simd-json = { version = "0.17", default-features = false, features = ["runtime-detection", "swar-number-parsing"] }
terminal-colorsaurus = { version = "1", features = ["anstyle"] }
terminal_size = "0.4"
unicode-truncate = "2"
unicode-width = "0.2"

#
# haven't decided which release is preferred yet
#

[profile.small]
codegen-units = 1
inherits = "release"
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"
