// Code generated by "stringer -type=Theme -trimprefix=Theme"; DO NOT EDIT.

package tennis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThemeAuto-0]
	_ = x[ThemeDark-1]
	_ = x[ThemeLight-2]
}

const _Theme_name = "AutoDarkLight"

var _Theme_index = [...]uint8{0, 4, 8, 13}

func (i Theme) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Theme_index)-1 {
		return "Theme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Theme_name[_Theme_index[idx]:_Theme_index[idx+1]]
}
