# This file was generated by GoReleaser. DO NOT EDIT.
cask "tennis" do
  name "tennis"
  desc "Stylish CSV tables in your terminal."
  homepage "https://github.com/gurgeous/tennis#readme"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tennis"
  bash_completion "completions/tennis.bash"
  zsh_completion "completions/_tennis"

  on_macos do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-amd64.tar.gz"
      sha256 "b6fe38c5dc7bc362a9580117bd3a929abc82d6d02eda921cf3aa120cfd4e3d38"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-darwin-arm64.tar.gz"
      sha256 "d80fdaf2df2bf6a0e07863e0aeffa06c86aee43a4f1926b6c518530e24b5af75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-amd64.tar.gz"
      sha256 "1f078791a4588cfb24491a53dd6783f55968750a2542a15555f2b9364f4efb25"
    end
    on_arm do
      url "https://github.com/gurgeous/tennis/releases/download/v#{version}/tennis-#{version}-linux-arm64.tar.gz"
      sha256 "f82ae2d77ec8e68cf1f2591113bbf39c18d22661e173410eecbb6b7de2629b14"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tennis"]
    end
  end

  # No zap stanza required
end
