name: ci

on:
  pull_request:
    paths-ignore: [README.md]
  push:
    branches: [$default-branch]
    paths-ignore: [README.md]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref_name}}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix: { platform: [ubuntu-latest, macos-latest] }
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - uses: taiki-e/install-action@just
      - run: just ci
